config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#index'
  resources :leagues do
    resources :games
    resources :teams do
      resources :players, except: :index
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
	belongs_to :league
end

app/models/league.rb
class League < ApplicationRecord
	has_many :games
	has_many :teams

	validates :length, 
				numericality: {
					less_than: 52,
					greater_than: 1,
					only_integer: true
				}
	validates :day_of_the_week,
				inclusion: {
					in: %w(Sunday Monday Tuesday Wednesday Thursday Friday Saturday),
					message: "%{value} is not a valid day of the week."
					}
	validates :sheets,
				numericality: {
					greater_than: 1,
					only_integer: true
				}
	validates :manager, presence: true

	def generate_games
		length.times do |i|
			date = start_date + (7 * i)
			sheets.times do |sheet|
				self.games.create(start_date: date, start_time: game_start_time, sheet: sheet+1)
			end
		end
	end
end

app/models/player.rb
class Player < ApplicationRecord
	belongs_to :team

	validates :first_name, presence: true
	validates :last_name, presence: true

	def full_name
		"#{first_name} #{last_name}"
	end
end

app/models/team.rb
class Team < ApplicationRecord
	belongs_to :league
	has_many :players

	def get_lead
		self.players.each do |player|
			if player.position == 'lead'
				return player
			end
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @leagues = League.all
    @upcoming_games = []
    @leagues.each do |league|
      @upcoming_games = @upcoming_games + get_upcoming_games(league)
    end
    @upcoming_games
  end

  private

  def get_upcoming_games(league)
    next_week = Time.now + 7
    upcoming_games = []
    league.games.all.each do |game|
      if game.start_date < next_week
        upcoming_games << game
      end
    end
    upcoming_games
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @league = League.find(params[:league_id])
    @games = @league.games.all
  end

  def show
    @league = League.find(params[:league_id])
    @game = @league.games.find(params[:id])
  end
  
  def new
    @league = League.find(params[:league_id])
  end

  def create
    @league = League.find(params[:league_id])
    @game = @league.games.create(game_params)
    redirect_to league_game_path(@league, @game)
  end

  def edit
    @league = League.find(params[:league_id])
    @game = @league.games.find(params[:id])
  end

  def update
    @league = League.find(params[:league_id])
    @game = @league.games.update(game_params)
    redirect_to league_game_path(@league, @game)
  end

  def destroy
    @league = League.find(params[:league_id])
    @game = @league.games.find(params[:id])
    @game.destroy
    redirect_to league_games_path(@league)
  end

  private
  def game_params
    params.require(:game).permit(:team_1, :team_2, :team_1_score, :team_2_score,
                                 :number_of_ends, :start_date, :start_time, :sheet)
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController

	def index
		@leagues = League.all
	end

	def show
		@league = League.find(params[:id])
	end

	def new
		@league = League.new
	end

	def create
		@league = League.new(league_params)
		if @league.save
			@league.generate_games
			redirect_to @league
		else
			render 'new'
		end
	end

	def edit
		@league = League.find(params[:id])
	end

	def update
		@league = League.find(params[:id])
		if @league.update(league_params)
			redirect_to @league
		else
			render 'new'
		end
	end

	def destroy
		@league = League.find(params[:id])
		@league.destroy
		redirect_to leagues_path
	end

	private

	def league_params
		params.require(:league).permit(:length, :day_of_the_week, :sheets, :manager, :start_date, :end_date, :game_start_time)
	end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def new
    @player = Player.new
    @team = Team.find(params[:team_id])
    @league = League.find(params[:league_id])
  end

  def create
    @league = League.find(params[:league_id])
    @team = @league.teams.find(params[:team_id])
    @player = @team.players.create(player_params)
    redirect_to league_team_path(@league, @team)
  end

  def show
    @league = League.find(params[:league_id])
    @team = @league.teams.find(params[:team_id])
    @player = @team.players.find(params[:id])
  end

  def edit
    @league = League.find(params[:league_id])
    @team = @league.teams.find(params[:team_id])
    @player = @team.players.find(params[:id])
  end

  def update
    @league = League.find(params[:league_id])
    @team = @league.teams.find(params[:team_id])
    @player = @team.players.update(player_params)
    redirect_to league_team_player_path(@league, @team, @player)
  end

  def destroy
    @league = League.find(params[:league_id])
    @team = @league.teams.find(params[:team_id])
    @team.players.destroy(params[:id])
    redirect_to league_team_path(@league, @team)
  end

  private
  def player_params
    params.require(:player).permit(:league_id, :team_id, :first_name, :last_name, :position, :member)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @league = League.find(params[:league_id])
    @teams = @league.teams.all
  end

  def show
    @league = League.find(params[:league_id])
    @team = @league.teams.find(params[:id])
  end

  def new
    @league = League.find(params[:league_id])
  end

  def create
    @league = League.find(params[:league_id])
    @team = @league.teams.create(team_params)
    redirect_to league_team_path(@league, @team)
  end

  def edit
    @league = League.find(params[:league_id])
    @team = @league.teams.find(params[:id])
  end

  def update
    @league = League.find(params[:league_id])
    @team = @league.teams.update(team_params)
    redirect_to league_team_path(@team)
  end

  def destroy
    @league = League.find(params[:league_id])
    @league.teams.find(params[:id]).destroy
    redirect_to league_teams_path
  end

  private

  def team_params
    params.require(:team).permit(:league_id, :team_name, :lead, :second, :vice, :skip)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/dashboard/index.html.erb
<div class="container-fluid col-sm-10 col-sm-offset-1">
  <h1 class="page-header">Club Dashboard</h1>
  <%= link_to 'View All Leagues', leagues_path %>

  <h2>Upcoming Games</h2>
  <div class="table-responsive">
    <table class="table table-hover">
      <th>League</th><th>Date</th><th>Time</th><th>Sheet</th><th>Team 1</th><th>Team 2</th>
      <% @upcoming_games.each do |game| %>
        <tr>
          <td><%= link_to game.league.day_of_the_week, league_path(game.league) %></td>
          <td><%= game.start_date %></td>
          <td><%= game.start_time %></td>
          <td><%= game.sheet %></td>
          <td><%= game.team_1 %></td>
          <td><%= game.team_2 %></td>
        </tr>
      <% end %>
    </table>
  </div>

  <div class="col-sm-10">
    <% @leagues.each do |league| %>
      <div class="col-sm-4">
        <h2 class="sub-header"><%= league.day_of_the_week %> League Teams</h2>
          <% league.teams.each do |team| %>
            <h3><%= link_to team.team_name, league_team_path(league, team) %></h3>
              <table class="table table-hover">
                <% team.players.each do |player| %>
                  <tr>
                    <td><strong><%= player.position %></strong></td>
                    <td><%= player.full_name %></td>
                    <td>
                    <% if player.member %>
                      Member
                    <% else %>
                      Non-member
                    <% end %>
                    </td>
                  </tr>
                <% end %>
              </table>
          <% end %>
        </div>
    <% end %>
  </div>
</div>

app/views/games/edit.html.erb
<h1>Edit game <%=@game.id %> of <%= @league.day_of_the_week %> League</h1>

<%= form_with(model: [@league, @game]) do |form| %>
    <p>
      <%= form.label :start_date %><br>
      <%= form.date_field :start_date %>
    </p>
    <p>
      <%= form.label :start_time %><br>
      <%= form.time_field :start_time %>
    </p>
    <p>
      <%= form.label :sheet %><br>
      <%= form.number_field :sheet %>
    </p>
    <p>
      <%= form.label :team_1, 'Yellow Team' %><br>
      <%= form.text_field :team_1 %>
    </p>
    <p>
      <%= form.label :team_2, 'Blue Team' %><br>
      <%= form.text_field :team_2 %>
    </p>
    <p>
      <%= form.label :team_1_score, 'Yellow Team Score' %><br>
      <%= form.number_field :team_1_score %>
    </p>
    <p>
      <%= form.label :team_2_score, 'Blue Team Score' %><br>
      <%= form.number_field :team_2_score %>
    </p>
    <p>
      <%= form.submit %>
    </p>
<% end %>
<%= link_to 'Back to game', league_game_path(@league, @game) %>

app/views/games/index.html.erb
<h1>All Games</h1>

<%= link_to 'Back to the league', league_path(@league) %>

<table>
  <tr>
    <th>Start Time</th>
    <th>Sheet</th>
  </tr>
  <% @games.each do |game| %>
    <tr>
      <td><%= game.start_date %></td>
      <td><%= game.start_time %></td>
      <td><%= game.sheet %></td>
      <td><%= link_to 'View', league_game_path(@league, game) %></td>
      <td><%= link_to 'Edit', edit_league_game_path(@league, game) %></td>
      <td><%= link_to 'Delete', league_game_path(@league, game), method: :delete, data: { confirm: 'Are you sure>'} %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Add new game', new_league_game_path(@league) %>

app/views/games/new.html.erb
<h1>Add a game to <%= @league.day_of_the_week %> League</h1>

  <%= form_with(model: [@league, @league.games.build]) do |form| %>
    <p>
      <%= form.label :start_date %><br>
      <%= form.date_field :start_date %>
    </p>
    <p>
      <%= form.label :start_time %><br>
      <%= form.time_field :start_time %>
    </p>
    <p>
      <%= form.label :sheet %><br>
      <%= form.number_field :sheet %>
    </p>
    <p>
      <%= form.label :team_1, 'Yellow Team' %><br>
      <%= form.text_field :team_1 %>
    </p>
    <p>
      <%= form.label :team_2, 'Blue Team' %><br>
      <%= form.text_field :team_2 %>
    </p>
    <p>
      <%= form.label :team_1_score, 'Yellow Team Score' %><br>
      <%= form.number_field :team_1_score %>
    </p>
    <p>
      <%= form.label :team_2_score, 'Blue Team Score' %><br>
      <%= form.number_field :team_2_score %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>
<%= link_to 'Back to Games', league_games_path(@league) %>

app/views/games/show.html.erb
<h1><%= @league.day_of_the_week %> League, Game <%= @game.id %></h1>
 <table>
   <tr>
     <td><strong>Start Date</strong></td><td><%= @game.start_date %></td>
   </tr>
   <tr>
     <td><strong>Start Time</strong></td><td><%= @game.start_time %></td>
   </tr>
   <tr>
     <td><strong>Sheet</strong></td><td><%= @game.sheet %></td>
   </tr>
   <tr>
     <td><strong>Yellow Team</strong></td><td><%= @game.team_1 %></td>
   </tr>
   <tr>
     <td><strong>Blue Team</strong></td><td><%= @game.team_2 %></td>
   </tr>
     <tr>
     <td><strong>Yellow Team Score</strong></td><td><%= @game.team_1_score %></td>
   </tr>
     <tr>
     <td><strong>Blue Team Score</strong></td><td><%= @game.team_2_score %></td>
   </tr>
 </table>
<%= link_to 'Back to Games', league_games_path(@league) %>
<%= link_to 'Edit', edit_league_game_path(@league, @game) %>
<%= link_to 'Delete', league_game_path(@league, @game), method: :delete, data:{ confirm: 'Are you sure?'} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CurlingOnRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/leagues/_form.html.erb
<%= form_with scope: :league, url: leagues_path, local: true do |form| %>
		
		<% if @league.errors.any? %>
			<% @league.errors.full_messages.each do |error| %>
				<ul><%= error %></ul>
			<% end %>
		<% end %>

		<p>
			<%= form.label :length %>
			<%= form.text_field :length %>
		</p>
		<p>
			<%= form.label :day_of_the_week %>
			<%= form.text_field :day_of_the_week %>
		</p>
		<p>
			<%= form.label :sheets %>
			<%= form.text_field :sheets %>
		</p>
		<p>
			<%= form.label :manager %>
			<%= form.text_field :manager %>
		</p>
    <p>
      <%= form.label :start_date %>
      <%= form.date_field :start_date %>
    </p>
    <p>
      <%= form.label :end_date %>
      <%= form.date_field :end_date %>
    </p>
    <p>
      <%= form.label :game_start_time %>
      <%= form.time_field :game_start_time %>
    </p>
		<p>
			<%= form.submit %>
		</p>
	<% end %>

app/views/leagues/edit.html.erb
<h1>Edit <%= @league.day_of_the_week %> League </h1>

<%= form_with model: @league do |form| %>

    <% if @league.errors.any? %>
        <% @league.errors.full_messages.each do |error| %>
            <ul><%= error %></ul>
        <% end %>
    <% end %>

    <p>
      <%= form.label :length %>
      <%= form.text_field :length %>
    </p>
    <p>
      <%= form.label :day_of_the_week %>
      <%= form.text_field :day_of_the_week %>
    </p>
    <p>
      <%= form.label :sheets %>
      <%= form.text_field :sheets %>
    </p>
    <p>
      <%= form.label :manager %>
      <%= form.text_field :manager %>
    </p>
    <p>
      <%= form.label :start_date %>
      <%= form.date_field :start_date %>
    </p>
    <p>
      <%= form.label :end_date %>
      <%= form.date_field :end_date %>
    </p>
    <p>
      <%= form.label :game_start_time %>
      <%= form.time_field :game_start_time %>
    </p>
    <p>
      <%= form.submit %>
    </p>
<% end %>

app/views/leagues/index.html.erb
<h1>Leagues</h1>
<%= link_to 'Back to Dashboard', root_path %>
<br>

<table>
	<tr>
		<th>Day of the week</th>
		<th>Number of weeks</th>
		<th>Number of sheets</th>
		<th>League Manager</th>
	</tr>

	<% @leagues.each do |league| %>
		<tr>
			<td><%= league.day_of_the_week %></td>
			<td><%= league.length %></td>
			<td><%= league.sheets %></td>
			<td><%= league.manager %></td>
      <td><%= link_to 'View', league_path(league) %></td>
			<td><%= link_to 'Edit', edit_league_path(league) %>
      <td><%= link_to 'Delete', league_path(league), method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
	<% end %>
</table>

<%= link_to 'Create New League', new_league_path %>

app/views/leagues/new.html.erb
<h1>Create a new league</h1>

<%= render 'form' %>

app/views/leagues/show.html.erb
<h1><%= @league.day_of_the_week %> <%= @league.game_start_time %> League</h1>

<h2>League Info</h2>

<table>
  <tr>
    <td><strong># of Weeks</strong></td><td><%= @league.length %></td>
  </tr>
  <tr>
    <td><strong>Day of the week</strong></td><td><%= @league.day_of_the_week %></td>
  </tr>
  <tr>
    <td><strong>Game Start Time</strong></td><td><%= @league.game_start_time %></td>
  </tr>
  <tr>
    <td><strong># of sheets</strong></td><td><%= @league.sheets %></td>
  </tr>
  <tr>
    <td><strong>League Manager</strong></td><td><%= @league.manager %></td>
  </tr>
  <tr>
    <td><strong>Start Date</strong></td><td><%= @league.start_date %></td>
  </tr>
  <tr>
    <td><strong>End Date</strong></td><td><%= @league.end_date %></td>
  </tr>
  <tr>
    <td><strong>Teams</strong></td><td><%= link_to 'View', league_teams_url(@league) %></td>
  </tr>
  <tr>
    <td><strong>Games</strong></td><td><%= link_to 'View', league_games_url(@league) %></td>
  </tr>

</table>

<%= link_to 'Back to Leagues', leagues_path %>
<%= link_to 'Edit', edit_league_path(@league) %>
<%= link_to 'Delete', league_path(@league), method: :delete, data: { confirm: 'Are you sure?'} %>

app/views/players/edit.html.erb
<h1>Update <%= @player.full_name %></h1>

<%= form_with model: [@league, @team, @player] do |form| %>
    <p>
      <%= form.label :first_name %>
      <%= form.text_field :first_name %>
    </p>
    <p>
      <%= form.label :last_name %>
      <%= form.text_field :last_name %>
    </p>
    <p>
      <%= form.label :position %>
      <%= form.text_field :position %>
    </p>
    <p>
      <%= form.check_box :member %>
      <%= form.label :member, "currently a member?" %>
    </p>
    <p>
      <%= form.submit %>
    </p>

<% end %>

app/views/players/new.html.erb
<h1>Add a new player to <%= @team.team_name %></h1>

  <%= form_with model: [@league, @team, @team.players.build] do |form| %>
  <p>
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </p>
  <p>
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </p>
  <p>
    <%= form.label :position %>
    <%= form.text_field :position %>
  </p>
  <p>
    <%= form.check_box :member %>
    <%= form.label :member, "currently a member?" %>
  </p>
  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/players/show.html.erb
<h1><%= @player.first_name %> <%= @player.last_name %></h1>

<table>
  <tr>
    <td><strong>First Name</strong></td>
    <td><%= @player.first_name %></td>
  </tr>
  <tr>
    <td><strong>Last Name</strong></td>
    <td><%= @player.last_name %></td>
  </tr>
  <tr>
    <td><strong>Position</strong></td>
    <td><%= @player.position %></td>
  </tr>
  <tr>
    <td><strong>Current Member?</strong></td>
    <td><%= @player.member %></td>
  </tr>
</table>

<%= link_to 'Back to Team', league_team_path(@league, @team) %>
<%= link_to 'Edit', edit_league_team_player_path(@league, @team, @player) %>
<%= link_to 'Delete', league_team_player_path(@league, @team, @player), method: :delete, data: { confirm: 'Are you sure?'} %>